/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package paintbasico;

import java.awt.Color;
import java.awt.Point;
import sm.jltr.iu.Lienzo;

/**
 * Clase que representa una ventana interna en la aplicación.
 * @author torres
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    
    // no lo inicializo, preguntar como, algo segundario
    private VentanaPrincipal ventanaPrincipal;
        
    /**
     * Constructor de la clase VentanaInterna.
     * Inicializa los componentes de la ventana interna y establece su tamaño inicial y color de fondo.
     */
    public VentanaInterna() {
        initComponents();
        this.setSize(300,300); // tamaño de inicializacion
        this.setBackground(Color.red); // no le hace caso
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollDerecha = new javax.swing.JScrollBar();
        lienzo = new sm.jltr.iu.Lienzo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().add(ScrollDerecha, java.awt.BorderLayout.LINE_END);

        lienzo.setAutoscrolls(true);
        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que maneja el evento de activación de la ventana interna.
     * Se podría utilizar para realizar alguna acción cuando la ventana interna se activa.
     * @param evt El evento de activación de la ventana interna.
     */
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // ???
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved
        // TODO add your handling code here:
        //Point posicion = evt.getPoint();
        //ventanaPrincipal.actualizarPosicionRatonEnLabel((int)posicion.getX(), (int)posicion.getY());
    }//GEN-LAST:event_lienzoMouseMoved

    /**
     * Método que devuelve el lienzo asociado a la ventana interna.
     * @return El lienzo asociado a la ventana interna.
     */
    public Lienzo getLienzo(){ 
        return lienzo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar ScrollDerecha;
    private sm.jltr.iu.Lienzo lienzo;
    // End of variables declaration//GEN-END:variables
}
