/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formasavanzadas;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Paint;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.font.TextAttribute;
import java.awt.geom.AffineTransform;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author torres
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
   
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        // aqui
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String []fuentesSistema = ge.getAvailableFontFamilyNames();
        //listaFuentes = new javax.swing.JComboBox(fuentesSistema);
        listaFuentes.setModel(new DefaultComboBoxModel(fuentesSistema));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraHerramientas = new javax.swing.JPanel();
        editarBoton = new javax.swing.JCheckBox();
        rellenoBoton = new javax.swing.JCheckBox();
        listaFuentes = new javax.swing.JComboBox<>();
        efectoventanaBoton = new javax.swing.JCheckBox();
        lienzo = new formasavanzadas.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        barraHerramientas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barraHerramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        editarBoton.setText("Editar");
        editarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(editarBoton);

        rellenoBoton.setText("Relleno");
        rellenoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rellenoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraHerramientas.add(rellenoBoton);

        listaFuentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaFuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFuentesActionPerformed(evt);
            }
        });
        barraHerramientas.add(listaFuentes);

        efectoventanaBoton.setText("Efecto ventana");
        efectoventanaBoton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        efectoventanaBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        efectoventanaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectoventanaBotonActionPerformed(evt);
            }
        });
        barraHerramientas.add(efectoventanaBoton);

        getContentPane().add(barraHerramientas, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaFuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFuentesActionPerformed
        // TODO add your handling code here:
        // accion sobre la lista desplegable 
        System.out.println("Cambio de fuente");
        String fuenteSeleccionada = (String) listaFuentes.getSelectedItem(); // Obtener la fuente seleccionada
        this.lienzo.setTipoFuente(fuenteSeleccionada);
        System.out.println("Fuente Seleccionada " + this.lienzo.getTipoFuente());

    }//GEN-LAST:event_listaFuentesActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       
    }//GEN-LAST:event_formMouseMoved

    private void efectoventanaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectoventanaBotonActionPerformed
        // TODO add your handling code here:
        // cuidado con esto 
        this.lienzo.setVentanaClipActiva(!this.lienzo.getVentanaClipActiva());
    }//GEN-LAST:event_efectoventanaBotonActionPerformed

    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraHerramientas;
    private javax.swing.JCheckBox editarBoton;
    private javax.swing.JCheckBox efectoventanaBoton;
    private formasavanzadas.Lienzo lienzo;
    private javax.swing.JComboBox<String> listaFuentes;
    private javax.swing.JCheckBox rellenoBoton;
    // End of variables declaration//GEN-END:variables
}
