/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lineasypuntos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author torres
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    // variables
    private ArrayList<Point> puntos = new ArrayList<>();
    private Point puntoInicial = null;
    private Point puntoFinal = null;
    
    
    // override al paint
    @Override
    public void paint(Graphics g){
       // 0. sobrecarga
        super.paint(g);

        // 1. Dibujar puntos
        g.setColor(Color.BLUE);
        for (Point punto : puntos) {
            g.fillOval(punto.x - 5 , punto.y - 5 , 10, 10); 
        }

        // 2. Dibujar línea mientras se arrastra el ratón
        if (puntoInicial != null && puntoFinal != null) {
            g.setColor(Color.RED);
            g.drawLine(puntoInicial.x, puntoInicial.y, puntoFinal.x, puntoFinal.y); 
            
            /*
                int x = Math.min(puntoInicial.x, puntoFinal.x);
                int y = Math.min(puntoInicial.y, puntoFinal.y);
                int ancho = Math.abs(puntoFinal.x - puntoInicial.x);
                int alto = Math.abs(puntoFinal.y - puntoInicial.y);
            
                // Dibuja un óvalo utilizando el ancho definido por los puntos iniciales y finales
                g.drawOval(x, y, ancho, alto);
            */
        }
        
            
    };

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        puntoInicial = new Point(evt.getX(), evt.getY());
        puntos.add(puntoInicial);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        puntoFinal = new Point(evt.getX(), evt.getY());
        repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        puntoFinal = new Point(evt.getX(), evt.getY());
        puntos.add(puntoFinal);
        repaint();
    }//GEN-LAST:event_formMouseReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
