/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemploeventos;

import java.awt.Color;

/**
 *
 * @author torres
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botón = new javax.swing.JToggleButton();
        Boton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(formListener);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Botón.setText("Boton 1");
        Botón.addMouseMotionListener(formListener);
        Botón.addMouseListener(formListener);
        getContentPane().add(Botón, new java.awt.GridBagConstraints());

        Boton2.setText("Boton 2");
        Boton2.addMouseListener(formListener);
        Boton2.addActionListener(formListener);
        getContentPane().add(Boton2, new java.awt.GridBagConstraints());

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == Boton2) {
                VentanaPrincipal.this.Boton2ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Botón) {
                VentanaPrincipal.this.BotónMouseClicked(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == Boton2) {
                VentanaPrincipal.this.Boton2MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Botón) {
                VentanaPrincipal.this.BotónMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Botón) {
                VentanaPrincipal.this.BotónMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Botón) {
                VentanaPrincipal.this.BotónMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void BotónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónMouseClicked
        Botón.setBackground(Color.red);
    }//GEN-LAST:event_BotónMouseClicked

    private void BotónMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónMouseEntered
        Botón.setBackground(Color.blue);
    }//GEN-LAST:event_BotónMouseEntered

    private void BotónMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónMouseExited
        Botón.setBackground(Color.green);
    }//GEN-LAST:event_BotónMouseExited

    private void BotónMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónMouseDragged
        Botón.setBackground(Color.orange);
    }//GEN-LAST:event_BotónMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        getContentPane().setBackground(new Color(148, 0, 211));             
    }//GEN-LAST:event_formMouseClicked

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        Boton2.setBackground(Color.orange);
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        getContentPane().setBackground(new Color(148, 0, 211));
    }//GEN-LAST:event_Boton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton2;
    private javax.swing.JToggleButton Botón;
    // End of variables declaration//GEN-END:variables
}
